(() => {
  const cfg=window.PAWBUDGET_CONFIG;
  const $=id=>document.getElementById(id);
  const $$=sel=>[...document.querySelectorAll(sel)];
  const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
  const money0=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v||0));
  const today=()=>new Date().toISOString().slice(0,10);
  const escapeHtml=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const toast=$('toast'); let toastTimer;
  function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
  if(!window.supabase||!cfg?.supabaseUrl||!cfg?.supabaseKey){$('authMessage').textContent='PawBudget configuration missing.';$('authMessage').className='auth-message error';return}
  const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey);
  const state={session:null,profile:null,settings:null,categories:[],subcategories:[],transactions:[],budgets:[],goals:[],contributions:[],debts:[],debtPayments:[],dashboardPeriod:'month',dashboardMonth:new Date(),historyPage:1,historyPageSize:20,charts:{},expenseDrill:{category:null,subcategory:null,merchant:null}};
  const chartColors=['#86bbf4','#ff8f9f','#fac66c','#cd82e8','#7e69e4','#65c8a3','#f0a84b','#6cb1b2','#ff7282','#a3c46b','#83d1e8','#c8a3f3'];

  // AUTH — Anna-only. No public signup and no visible email field.
  const OWNER_EMAIL = cfg.ownerEmail;
  function setAuthMessage(text='',type=''){$('authMessage').textContent=text;$('authMessage').className=`auth-message ${type}`.trim()}
  $('togglePassword').onclick=()=>{$('authPassword').type=$('authPassword').type==='password'?'text':'password'};
  $('authForm').onsubmit=async e=>{
    e.preventDefault();
    const password=$('authPassword').value;
    if(!OWNER_EMAIL){setAuthMessage('Owner login is not configured.','error');return}
    if(password.length<6){setAuthMessage('Enter your PawBudget password.','error');return}
    const b=$('primaryAuthButton');
    b.disabled=true;
    b.textContent='Signing in…';
    setAuthMessage();
    try{
      const {data,error}=await db.auth.signInWithPassword({email:OWNER_EMAIL,password});
      if(error) throw error;
      await enterApp(data.session);
    }catch(err){
      setAuthMessage(err.message||'Sign in failed.','error');
    }finally{
      b.disabled=false;
      b.textContent='Sign in';
    }
  };
  $('forgotPassword').onclick=async()=>{
    if(!OWNER_EMAIL)return setAuthMessage('Owner recovery email is not configured.','error');
    $('forgotPassword').disabled=true;
    setAuthMessage('Sending a secure reset link…','success');
    try{
      const {error}=await db.auth.resetPasswordForEmail(OWNER_EMAIL,{redirectTo:cfg.siteUrl});
      if(error)throw error;
      setAuthMessage('Reset link sent to Anna’s recovery email. Open that email to choose a new password.','success');
    }catch(err){
      setAuthMessage(err.message||'Could not send password reset email.','error');
    }finally{
      $('forgotPassword').disabled=false;
    }
  };

  async function signOut(){await db.auth.signOut();location.reload()}
  $('signOutButton').onclick=signOut;$('settingsSignOut').onclick=signOut;

  async function enterApp(session){state.session=session;$('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('floatingAddButton').classList.remove('hidden');await loadAll();openPage('dashboard')}
  async function loadAll(){try{await Promise.all([loadProfile(),loadCategories(),loadTransactions(),loadBudgets(),loadSavings(),loadDebts()]);applyTheme();renderAll()}catch(err){console.error(err);$('cloudStatus').innerHTML='<span style="background:#e34e62"></span> Data error';showToast('Connected, but some data failed to load.')}}
  async function loadProfile(){const uid=state.session.user.id;const [{data:p},{data:s}]=await Promise.all([db.from('profiles').select('*').eq('id',uid).maybeSingle(),db.from('user_settings').select('*').eq('user_id',uid).maybeSingle()]);state.profile=p||{display_name:'Anna',currency:'USD',date_format:'MM/DD/YYYY'};state.settings=s||{theme:'system'};$('profileName').textContent=`${state.profile.display_name||'Anna'}!`;$('heroName').textContent=state.profile.display_name||'Anna';$('settingsName').value=state.profile.display_name||'Anna';$('themeSelect').value=state.settings.theme||'system'}
  async function loadCategories(){const uid=state.session.user.id;const [{data:c,error:ce},{data:s,error:se}]=await Promise.all([db.from('categories').select('*').eq('user_id',uid).eq('is_archived',false).order('sort_order'),db.from('subcategories').select('*').eq('user_id',uid).eq('is_archived',false).order('sort_order')]);if(ce)throw ce;if(se)throw se;state.categories=c||[];state.subcategories=s||[];populateCategorySelects()}
  async function loadTransactions(){const {data,error}=await db.from('transactions').select('*,categories(id,name,icon,color),subcategories(id,name)').eq('user_id',state.session.user.id).order('transaction_date',{ascending:false}).limit(5000);if(error)throw error;state.transactions=data||[]}
  async function loadBudgets(){const {data,error}=await db.from('budgets').select('*,categories(id,name,icon,color)').eq('user_id',state.session.user.id).order('budget_month',{ascending:false});if(error)throw error;state.budgets=data||[]}
  async function loadSavings(){const uid=state.session.user.id;const [{data:g,error:ge},{data:c,error:ce}]=await Promise.all([db.from('savings_goals').select('*').eq('user_id',uid).order('created_at',{ascending:false}),db.from('savings_contributions').select('*').eq('user_id',uid).order('contribution_date',{ascending:false})]);if(ge)throw ge;if(ce)throw ce;state.goals=g||[];state.contributions=c||[]}
  async function loadDebts(){const uid=state.session.user.id;const [{data:d,error:de},{data:p,error:pe}]=await Promise.all([db.from('debts').select('*').eq('user_id',uid).order('created_at',{ascending:false}),db.from('debt_payments').select('*').eq('user_id',uid).order('payment_date',{ascending:false})]);if(de)throw de;if(pe)throw pe;state.debts=d||[];state.debtPayments=p||[]}

  function renderAll(){renderDashboard();renderIncome();renderExpenses();renderBudget();renderSavings();renderDebts();renderReports();renderHistory();renderSettings()}
  function dateRange(period,base=new Date()){const y=base.getFullYear(),m=base.getMonth();let start,end=new Date(y,m+1,0);if(period==='month')start=new Date(y,m,1);else if(period==='lastMonth'){start=new Date(y,m-1,1);end=new Date(y,m,0)}else if(period==='3m')start=new Date(y,m-2,1);else if(period==='6m')start=new Date(y,m-5,1);else if(period==='year')start=new Date(y,0,1);else if(period==='lastYear'){start=new Date(y-1,0,1);end=new Date(y-1,11,31)}else return {start:null,end:null};const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return {start:iso(start),end:iso(end)}}
  function inRange(rows,period,base=state.dashboardMonth){const r=dateRange(period,base);if(!r.start)return rows;return rows.filter(x=>x.transaction_date>=r.start&&x.transaction_date<=r.end)}
  const sum=(rows,field='amount')=>rows.reduce((s,x)=>s+Number(x[field]||0),0);
  const categoryName=t=>t.categories?.name||state.categories.find(c=>c.id===t.category_id)?.name||'Uncategorized';
  const subcategoryName=t=>t.subcategories?.name||state.subcategories.find(s=>s.id===t.subcategory_id)?.name||'Other';
  function groupBy(rows,keyFn){const out={};rows.forEach(x=>{const k=keyFn(x);out[k]=(out[k]||0)+Number(x.amount||0)});return out}
  function monthKey(d){return d.slice(0,7)}
  function monthLabels(n=6){const arr=[];const now=new Date();for(let i=n-1;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);arr.push({key:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,label:d.toLocaleString('en-US',{month:'short'})})}return arr}
  function destroyChart(id){if(state.charts[id]){state.charts[id].destroy();delete state.charts[id]}}
  function makeChart(id,config){destroyChart(id);const el=$(id);if(!el||!window.Chart)return;state.charts[id]=new Chart(el,config)}
  const chartBase={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{boxWidth:10,usePointStyle:true,font:{size:10}}}},scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{grid:{color:'rgba(120,130,150,.12)'},ticks:{font:{size:9}}}}};

  // DASHBOARD
  function renderDashboard(){const rows=inRange(state.transactions,state.dashboardPeriod);const incomeRows=rows.filter(t=>t.transaction_type==='income'),expenseRows=rows.filter(t=>t.transaction_type==='expense');const income=sum(incomeRows),spent=sum(expenseRows),rec=expenseRows.filter(t=>t.is_recurring);$('kpiIncome').textContent=money0(income);$('kpiSpent').textContent=money0(spent);$('kpiBills').textContent=money0(sum(rec));$('billsCaption').textContent=`${rec.length} recurring`;const savingsRows=state.contributions.filter(c=>{const r=dateRange(state.dashboardPeriod,state.dashboardMonth);return !r.start||(c.contribution_date>=r.start&&c.contribution_date<=r.end)});$('kpiSavings').textContent=money0(sum(savingsRows));const active=state.debts.filter(d=>d.status==='active');$('kpiDebt').textContent=money0(active.reduce((s,d)=>s+Number(d.monthly_payment||0),0));$('debtCaption').textContent=`${active.length} active payments`;$('kpiLeft').textContent=money0(income-spent);$('leftCaption').textContent=income?'Income minus spending':'No income in period';$('snapshotSubtitle').textContent=`Here’s your financial snapshot for ${periodLabel(state.dashboardPeriod,state.dashboardMonth)}.`;$('monthChip').textContent=`📅 ${state.dashboardMonth.toLocaleString('en-US',{month:'long',year:'numeric'})}`;renderTrendChart('dashboardTrendChart',6);renderCategoryChart('dashboardCategoryChart',expenseRows);renderDashboardBudget();renderRecent(rows);renderDashboardSavings();renderDashboardDebts();renderDashboardExplorer(expenseRows);renderInsight(expenseRows,income,spent)}
  function periodLabel(period,base){if(period==='month')return base.toLocaleString('en-US',{month:'long',year:'numeric'});if(period==='lastMonth'){const d=new Date(base.getFullYear(),base.getMonth()-1,1);return d.toLocaleString('en-US',{month:'long',year:'numeric'})}return ({'3m':'the last 3 months','6m':'the last 6 months','year':'this year','lastYear':'last year','all':'all time'})[period]||'selected period'}
  function renderTrendChart(id,n=6,typeFilter=null){const months=monthLabels(n),inc=[],exp=[];months.forEach(m=>{const r=state.transactions.filter(t=>monthKey(t.transaction_date)===m.key);inc.push(sum(r.filter(t=>t.transaction_type==='income')));exp.push(sum(r.filter(t=>t.transaction_type==='expense')))});makeChart(id,{type:'bar',data:{labels:months.map(x=>x.label),datasets:typeFilter==='income'?[{label:'Income',data:inc,backgroundColor:'#62cba1',borderRadius:6}]:typeFilter==='expense'?[{label:'Expenses',data:exp,backgroundColor:'#ff8196',borderRadius:6}]:[{label:'Income',data:inc,backgroundColor:'#62cba1',borderRadius:6},{label:'Expenses',data:exp,backgroundColor:'#ff8196',borderRadius:6}]},options:chartBase})}
  function renderCategoryChart(id,rows){const g=groupBy(rows,categoryName),entries=Object.entries(g).sort((a,b)=>b[1]-a[1]);makeChart(id,{type:'doughnut',data:{labels:entries.map(x=>x[0]),datasets:[{data:entries.map(x=>x[1]),backgroundColor:chartColors,borderWidth:2,borderColor:getComputedStyle(document.body).getPropertyValue('--card').trim()||'#fff'}]},options:{responsive:true,maintainAspectRatio:false,cutout:'62%',plugins:{legend:{position:'right',labels:{boxWidth:9,usePointStyle:true,font:{size:9}}}}}})}
  function renderDashboardBudget(){const month=`${state.dashboardMonth.getFullYear()}-${String(state.dashboardMonth.getMonth()+1).padStart(2,'0')}-01`;const budgets=state.budgets.filter(b=>b.budget_month===month);const rows=state.transactions.filter(t=>t.transaction_type==='expense'&&monthKey(t.transaction_date)===month.slice(0,7));const actual=groupBy(rows,categoryName);makeChart('dashboardBudgetChart',{type:'bar',data:{labels:budgets.map(b=>b.categories?.name||'Category'),datasets:[{label:'Budget',data:budgets.map(b=>Number(b.amount)),backgroundColor:'#ffd3dd',borderRadius:5},{label:'Actual',data:budgets.map(b=>actual[b.categories?.name]||0),backgroundColor:'#f56f84',borderRadius:5}]},options:chartBase})}
  function renderRecent(rows){const box=$('recentTransactions');const head='<div class="tr head"><span>Date</span><span>Merchant</span><span>Category</span><span>Amount</span></div>';if(!rows.length){box.innerHTML=head+'<div class="simple-empty">No transactions yet.</div>';return}box.innerHTML=head+rows.slice(0,6).map(t=>`<div class="tr"><span>${new Date(t.transaction_date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span><span>${escapeHtml(t.merchant||t.description||'Transaction')}</span><span>${escapeHtml(categoryName(t))}</span><b class="${t.transaction_type==='income'?'positive-amount':'negative-amount'}">${t.transaction_type==='income'?'+':'-'}${money(t.amount)}</b></div>`).join('')}
  function renderDashboardSavings(){const box=$('dashboardSavingsGoals');const active=state.goals.filter(g=>g.status==='active').slice(0,3);box.innerHTML=active.length?active.map(goalHtml).join(''):'<div class="simple-empty">No savings goals yet.</div>'}
  function renderDashboardDebts(){const box=$('dashboardDebtList');const active=state.debts.filter(d=>d.status==='active').slice(0,3);box.innerHTML=active.length?active.map(d=>`<div class="debt-row"><div class="debt-head"><strong>${escapeHtml(d.name)}</strong><span>${money0(d.current_balance)} remaining</span></div><div class="progress"><i style="width:${debtProgress(d)}%"></i></div></div>`).join(''):'<div class="simple-empty">No debt or EMI yet.</div>'}
  function renderDashboardExplorer(rows){const cats=Object.entries(groupBy(rows,categoryName)).sort((a,b)=>b[1]-a[1]);$('dashboardExplorerCategories').innerHTML=cats.length?cats.slice(0,7).map(([n,v])=>`<button class="explorer-item" data-cat="${escapeHtml(n)}"><span>${escapeHtml(n)}</span><b>${money0(v)}</b></button>`).join(''):'<div class="simple-empty">No expense activity yet.</div>';$$('#dashboardExplorerCategories .explorer-item').forEach(b=>b.onclick=()=>renderDashboardMerchants(b.dataset.cat,rows));if(cats.length)renderDashboardMerchants(cats[0][0],rows);else $('dashboardMerchantCard').innerHTML='<div class="simple-empty">No merchants yet.</div>'}
  function renderDashboardMerchants(cat,rows){$('dashboardBreadcrumb').textContent=`Expenses › ${cat} › Merchants`;const subset=rows.filter(t=>categoryName(t)===cat);const g=groupBy(subset,t=>t.merchant||'No merchant');$('dashboardMerchantCard').innerHTML='<div class="merchant-head"><strong>Top merchants</strong><span>Selected period</span></div>'+Object.entries(g).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([n,v])=>`<button class="merchant-item"><span>${escapeHtml(n)}</span><b>${money0(v)}</b></button>`).join('')}
  function renderInsight(rows,income,spent){const g=Object.entries(groupBy(rows,categoryName)).sort((a,b)=>b[1]-a[1]);if(!rows.length){$('insightText').textContent='Add expenses to unlock spending insights.';return}const top=g[0];const pct=income?spent/income*100:null;$('insightText').innerHTML=`Your highest category is <strong>${escapeHtml(top[0])}</strong> at <strong>${money0(top[1])}</strong>. ${pct!==null?`You spent ${pct.toFixed(0)}% of income in this period.`:''}`}

  // INCOME
  function renderIncome(){const income=state.transactions.filter(t=>t.transaction_type==='income'),now=new Date(),month=income.filter(t=>monthKey(t.transaction_date)===`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`),year=income.filter(t=>t.transaction_date.startsWith(String(now.getFullYear())));$('incomeMonth').textContent=money0(sum(month));$('incomeYear').textContent=money0(sum(year));const months=Object.values(groupBy(income,t=>monthKey(t.transaction_date)));$('incomeAverage').textContent=money0(months.length?months.reduce((a,b)=>a+b,0)/months.length:0);const monthly=Object.entries(groupBy(income,t=>monthKey(t.transaction_date))).sort((a,b)=>b[1]-a[1]);$('incomeHighest').textContent=money0(monthly[0]?.[1]||0);$('incomeHighestLabel').textContent=monthly[0]?.[0]||'—';renderTrendChart('incomeTrendChart',12,'income');const sources=Object.entries(groupBy(income,categoryName));makeChart('incomeSourceChart',{type:'doughnut',data:{labels:sources.map(x=>x[0]),datasets:[{data:sources.map(x=>x[1]),backgroundColor:chartColors}]},options:{responsive:true,maintainAspectRatio:false,cutout:'60%',plugins:{legend:{position:'right',labels:{boxWidth:9,usePointStyle:true,font:{size:9}}}}}});renderBasicTable('incomeTable',income.slice(0,100))}

  // EXPENSES & drilldown
  function renderExpenses(){const exp=state.transactions.filter(t=>t.transaction_type==='expense'),now=new Date(),key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,month=exp.filter(t=>monthKey(t.transaction_date)===key);$('expenseMonth').textContent=money0(sum(month));$('expenseDaily').textContent=money0(sum(month)/Math.max(1,now.getDate()));const largest=[...month].sort((a,b)=>b.amount-a.amount)[0];$('expenseLargest').textContent=money0(largest?.amount||0);const cats=Object.entries(groupBy(month,categoryName)).sort((a,b)=>b[1]-a[1]);$('expenseTopCategory').textContent=cats[0]?.[0]||'—';$('expenseTopCategoryAmount').textContent=money0(cats[0]?.[1]||0);renderTrendChart('expenseTrendChart',12,'expense');renderCategoryChart('expenseCategoryChart',month);renderExpenseDrill(month)}
  function renderExpenseDrill(rows){const categories=Object.entries(groupBy(rows,categoryName)).sort((a,b)=>b[1]-a[1]);$('expenseCategoryList').innerHTML='<h4>Categories</h4>'+ (categories.length?categories.map(([n,v])=>`<button class="side-item" data-cat="${escapeHtml(n)}"><span>${escapeHtml(n)}</span><b>${money0(v)}</b></button>`).join(''):'<div class="simple-empty">No expenses.</div>');$$('#expenseCategoryList .side-item').forEach(b=>b.onclick=()=>selectExpenseCategory(b.dataset.cat,rows));if(categories.length)selectExpenseCategory(state.expenseDrill.category&&categories.some(x=>x[0]===state.expenseDrill.category)?state.expenseDrill.category:categories[0][0],rows);else{$('expenseSubcategoryList').innerHTML='<h4>Subcategories</h4>';$('expenseMerchantList').innerHTML='<h4>Merchants</h4>';$('expenseDetailList').innerHTML='<h4>Transactions</h4>'}}
  function selectExpenseCategory(cat,rows){state.expenseDrill.category=cat;state.expenseDrill.subcategory=null;state.expenseDrill.merchant=null;$$('#expenseCategoryList .side-item').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));const subset=rows.filter(t=>categoryName(t)===cat);const subs=Object.entries(groupBy(subset,subcategoryName)).sort((a,b)=>b[1]-a[1]);$('expenseSubcategoryList').innerHTML='<h4>Subcategories</h4>'+subs.map(([n,v])=>`<button class="side-item" data-sub="${escapeHtml(n)}"><span>${escapeHtml(n)}</span><b>${money0(v)}</b></button>`).join('');$$('#expenseSubcategoryList .side-item').forEach(b=>b.onclick=()=>selectExpenseSubcategory(b.dataset.sub,subset));$('expenseBreadcrumb').textContent=`Expenses › ${cat}`;if(subs.length)selectExpenseSubcategory(subs[0][0],subset)}
  function selectExpenseSubcategory(sub,catRows){state.expenseDrill.subcategory=sub;$$('#expenseSubcategoryList .side-item').forEach(x=>x.classList.toggle('active',x.dataset.sub===sub));const subset=catRows.filter(t=>subcategoryName(t)===sub);const merchants=Object.entries(groupBy(subset,t=>t.merchant||'No merchant')).sort((a,b)=>b[1]-a[1]);$('expenseMerchantList').innerHTML='<h4>Merchants</h4>'+merchants.map(([n,v])=>`<button class="side-item" data-merchant="${escapeHtml(n)}"><span>${escapeHtml(n)}</span><b>${money0(v)}</b></button>`).join('');$$('#expenseMerchantList .side-item').forEach(b=>b.onclick=()=>selectExpenseMerchant(b.dataset.merchant,subset));$('expenseBreadcrumb').textContent=`Expenses › ${state.expenseDrill.category} › ${sub}`;if(merchants.length)selectExpenseMerchant(merchants[0][0],subset);else $('expenseDetailList').innerHTML='<h4>Transactions</h4><div class="simple-empty">No merchant activity.</div>'}
  function selectExpenseMerchant(merchant,subRows){state.expenseDrill.merchant=merchant;$$('#expenseMerchantList .side-item').forEach(x=>x.classList.toggle('active',x.dataset.merchant===merchant));const rows=subRows.filter(t=>(t.merchant||'No merchant')===merchant);$('expenseDetailList').innerHTML=`<h4>${escapeHtml(merchant)} · ${money0(sum(rows))}</h4>`+rows.map(t=>`<div class="detail-transaction"><span>${new Date(t.transaction_date+'T12:00:00').toLocaleDateString()}</span><b>${money(t.amount)}</b><small>${escapeHtml(t.description||subcategoryName(t))}</small></div>`).join('');$('expenseBreadcrumb').textContent=`Expenses › ${state.expenseDrill.category} › ${state.expenseDrill.subcategory} › ${merchant}`}

  // BUDGET
  function currentMonthISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
  function renderBudget(){const month=currentMonthISO(),budgets=state.budgets.filter(b=>b.budget_month===month),exp=state.transactions.filter(t=>t.transaction_type==='expense'&&monthKey(t.transaction_date)===month.slice(0,7)),spent=sum(exp),total=sum(budgets);$('budgetTotal').textContent=money0(total);$('budgetSpent').textContent=money0(spent);$('budgetRemaining').textContent=money0(total-spent);$('budgetUsed').textContent=total?`${(spent/total*100).toFixed(0)}%`:'0%';$('budgetMonthLabel').textContent=new Date(month+'T12:00:00').toLocaleString('en-US',{month:'long',year:'numeric'});const actual=groupBy(exp,categoryName);makeChart('budgetPageChart',{type:'bar',data:{labels:budgets.map(b=>b.categories?.name||'Category'),datasets:[{label:'Budget',data:budgets.map(b=>Number(b.amount)),backgroundColor:'#ffd3dd',borderRadius:6},{label:'Actual',data:budgets.map(b=>actual[b.categories?.name]||0),backgroundColor:'#f46f84',borderRadius:6}]},options:chartBase});$('budgetHealth').innerHTML=budgets.length?budgets.map(b=>{const name=b.categories?.name||'Category',a=actual[name]||0,p=Number(b.amount)?a/Number(b.amount)*100:0;return `<div class="health-row ${p>100?'over':''}"><div class="health-top"><strong>${escapeHtml(name)}</strong><span>${money0(a)} / ${money0(b.amount)} · ${p.toFixed(0)}%</span></div><div class="progress"><i style="width:${Math.min(100,p)}%"></i></div></div>`}).join(''):'<div class="simple-empty">No budgets set yet.</div>';$('budgetCards').innerHTML=budgets.length?budgets.map(b=>{const name=b.categories?.name||'Category',a=actual[name]||0;return `<div class="budget-card"><div class="budget-top"><strong>${escapeHtml(name)}</strong><span>${money0(b.amount)}</span></div><p>${money0(a)} spent · ${money0(Number(b.amount)-a)} remaining</p><button class="tiny-btn danger" data-delete-budget="${b.id}">Delete</button></div>`}).join(''):'<div class="simple-empty">Set your first monthly budget.</div>';$$('[data-delete-budget]').forEach(b=>b.onclick=()=>deleteBudget(b.dataset.deleteBudget))}

  // SAVINGS
  function goalSaved(id){return state.contributions.filter(c=>c.goal_id===id).reduce((s,c)=>s+Number(c.amount),0)}
  function goalHtml(g){const saved=goalSaved(g.id),pct=Number(g.target_amount)?Math.min(100,saved/Number(g.target_amount)*100):0;return `<div class="goal"><div class="goal-head"><strong>${escapeHtml(g.name)}</strong><span>${money0(saved)} / ${money0(g.target_amount)}</span></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}
  function renderSavings(){const active=state.goals.filter(g=>g.status==='active'),saved=state.goals.reduce((s,g)=>s+goalSaved(g.id),0),targets=state.goals.reduce((s,g)=>s+Number(g.target_amount||0),0);$('savingsTotalSaved').textContent=money0(saved);$('savingsTargetTotal').textContent=money0(targets);$('savingsActiveCount').textContent=active.length;$('savingsCompletion').textContent=targets?`${(saved/targets*100).toFixed(0)}%`:'0%';$('savingsGoalCards').innerHTML=state.goals.length?state.goals.map(g=>{const sv=goalSaved(g.id),pct=Number(g.target_amount)?Math.min(100,sv/Number(g.target_amount)*100):0;return `<article class="goal-card-large"><h3>${escapeHtml(g.name)}</h3><p>${g.target_date?`Target ${new Date(g.target_date+'T12:00:00').toLocaleDateString()}`:'No target date'}</p><strong>${money0(sv)} / ${money0(g.target_amount)}</strong><div class="progress"><i style="width:${pct}%"></i></div><div class="goal-actions"><button class="primary-small" data-contribute="${g.id}">＋ Add Money</button><button class="tiny-btn" data-complete-goal="${g.id}">Complete</button><button class="tiny-btn danger" data-delete-goal="${g.id}">Delete</button></div></article>`}).join(''):'<div class="simple-empty">Create your first savings goal.</div>';$$('[data-contribute]').forEach(b=>b.onclick=()=>openContribution(b.dataset.contribute));$$('[data-complete-goal]').forEach(b=>b.onclick=()=>completeGoal(b.dataset.completeGoal));$$('[data-delete-goal]').forEach(b=>b.onclick=()=>deleteGoal(b.dataset.deleteGoal))}

  // DEBTS
  function debtProgress(d){if(!Number(d.original_amount))return 0;return Math.max(0,Math.min(100,(1-Number(d.current_balance)/Number(d.original_amount))*100))}
  function renderDebts(){const active=state.debts.filter(d=>d.status==='active'),remaining=active.reduce((s,d)=>s+Number(d.current_balance||0),0),monthly=active.reduce((s,d)=>s+Number(d.monthly_payment||0),0),original=active.reduce((s,d)=>s+Number(d.original_amount||0),0);$('debtRemaining').textContent=money0(remaining);$('debtMonthly').textContent=money0(monthly);$('debtActiveCount').textContent=active.length;$('debtPaidTotal').textContent=money0(Math.max(0,original-remaining));$('debtCards').innerHTML=state.debts.length?state.debts.map(d=>`<article class="goal-card-large"><h3>${escapeHtml(d.name)}</h3><p>${escapeHtml(d.debt_type||'Debt')} · ${d.monthly_payment?`${money0(d.monthly_payment)}/month`:'No monthly amount'}</p><strong>${money0(d.current_balance)} remaining</strong><div class="progress"><i style="width:${debtProgress(d)}%"></i></div><div class="goal-actions"><button class="primary-small" data-pay-debt="${d.id}">Record Payment</button><button class="tiny-btn" data-paid-debt="${d.id}">Mark Paid</button><button class="tiny-btn danger" data-delete-debt="${d.id}">Delete</button></div></article>`).join(''):'<div class="simple-empty">Add your first debt or EMI.</div>';$$('[data-pay-debt]').forEach(b=>b.onclick=()=>openDebtPayment(b.dataset.payDebt));$$('[data-paid-debt]').forEach(b=>b.onclick=()=>markDebtPaid(b.dataset.paidDebt));$$('[data-delete-debt]').forEach(b=>b.onclick=()=>deleteDebt(b.dataset.deleteDebt))}

  // REPORTS
  function renderReports(){const period=$('reportPeriod')?.value||'month',rows=inRange(state.transactions,period,new Date()),inc=rows.filter(t=>t.transaction_type==='income'),exp=rows.filter(t=>t.transaction_type==='expense'),income=sum(inc),expenses=sum(exp);$('reportIncome').textContent=money0(income);$('reportExpenses').textContent=money0(expenses);$('reportNet').textContent=money0(income-expenses);$('reportSavingsRate').textContent=income?`${((income-expenses)/income*100).toFixed(1)}%`:'0%';renderReportTrend(rows);renderCategoryChart('reportCategoryChart',exp);const merchants=Object.entries(groupBy(exp,t=>t.merchant||'No merchant')).sort((a,b)=>b[1]-a[1]).slice(0,10);$('reportMerchants').innerHTML=merchants.length?merchants.map(([n,v],i)=>`<div class="rank-row"><span>#${i+1} ${escapeHtml(n)}</span><strong>${money0(v)}</strong></div>`).join(''):'<div class="simple-empty">No merchant data.</div>';const largest=[...exp].sort((a,b)=>b.amount-a.amount)[0],cats=Object.entries(groupBy(exp,categoryName)).sort((a,b)=>b[1]-a[1]);$('reportHighlights').innerHTML=[['Largest transaction',largest?`${escapeHtml(largest.merchant||categoryName(largest))} · ${money0(largest.amount)}`:'—'],['Top category',cats[0]?`${escapeHtml(cats[0][0])} · ${money0(cats[0][1])}`:'—'],['Transactions',String(rows.length)],['Average expense',exp.length?money0(expenses/exp.length):'$0']].map(([l,v])=>`<div class="highlight-row"><span>${l}</span><strong>${v}</strong></div>`).join('')}
  function renderReportTrend(rows){const g={};rows.forEach(t=>{const k=monthKey(t.transaction_date);g[k]=g[k]||{income:0,expense:0};g[k][t.transaction_type==='income'?'income':'expense']+=Number(t.amount)});const keys=Object.keys(g).sort();makeChart('reportTrendChart',{type:'line',data:{labels:keys,datasets:[{label:'Income',data:keys.map(k=>g[k].income),borderColor:'#56c79c',backgroundColor:'rgba(86,199,156,.12)',tension:.3},{label:'Expenses',data:keys.map(k=>g[k].expense),borderColor:'#f36f84',backgroundColor:'rgba(243,111,132,.1)',tension:.3}]},options:chartBase})}

  // HISTORY
  function historyFiltered(){let rows=[...state.transactions],q=$('historySearch').value.trim().toLowerCase(),type=$('historyType').value,cat=$('historyCategory').value,from=$('historyFrom').value,to=$('historyTo').value;if(q)rows=rows.filter(t=>`${t.merchant||''} ${t.description||''} ${t.notes||''} ${categoryName(t)} ${subcategoryName(t)}`.toLowerCase().includes(q));if(type!=='all')rows=rows.filter(t=>t.transaction_type===type);if(cat!=='all')rows=rows.filter(t=>t.category_id===cat);if(from)rows=rows.filter(t=>t.transaction_date>=from);if(to)rows=rows.filter(t=>t.transaction_date<=to);return rows}
  function renderHistory(){const rows=historyFiltered(),pages=Math.max(1,Math.ceil(rows.length/state.historyPageSize));state.historyPage=Math.min(state.historyPage,pages);const start=(state.historyPage-1)*state.historyPageSize,view=rows.slice(start,start+state.historyPageSize);$('historyTable').innerHTML=dataTableHtml(view,true);$('historyPageInfo').textContent=`Page ${state.historyPage} of ${pages} · ${rows.length} records`;$('historyPrev').disabled=state.historyPage<=1;$('historyNext').disabled=state.historyPage>=pages;$$('[data-edit-tx]').forEach(b=>b.onclick=()=>openEditTransaction(b.dataset.editTx));$$('[data-delete-tx]').forEach(b=>b.onclick=()=>deleteTransaction(b.dataset.deleteTx))}
  function dataTableHtml(rows,actions=false){if(!rows.length)return '<div class="simple-empty">No transactions found.</div>';return `<table class="data-table"><thead><tr><th>Date</th><th>Type</th><th>Merchant</th><th>Category</th><th>Subcategory</th><th>Description</th><th>Amount</th>${actions?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(t=>`<tr><td>${t.transaction_date}</td><td>${t.transaction_type}</td><td>${escapeHtml(t.merchant||'—')}</td><td>${escapeHtml(categoryName(t))}</td><td>${escapeHtml(subcategoryName(t))}</td><td>${escapeHtml(t.description||'—')}</td><td class="${t.transaction_type==='income'?'positive-amount':'negative-amount'}">${t.transaction_type==='income'?'+':'-'}${money(t.amount)}</td>${actions?`<td><div class="table-actions"><button class="tiny-btn" data-edit-tx="${t.id}">Edit</button><button class="tiny-btn danger" data-delete-tx="${t.id}">Delete</button></div></td>`:''}</tr>`).join('')}</tbody></table>`}
  function renderBasicTable(id,rows){$(id).innerHTML=dataTableHtml(rows,false)}

  // SETTINGS
  function renderSettings(){const catSel=$('historyCategory');catSel.innerHTML='<option value="all">All categories</option>'+state.categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');const groups=state.categories.map(c=>{const subs=state.subcategories.filter(s=>s.category_id===c.id);return `<div class="category-group"><div class="category-group-head"><strong>${escapeHtml(c.icon||'')} ${escapeHtml(c.name)} <small>(${c.category_type})</small></strong><button class="tiny-btn danger" data-archive-category="${c.id}">Archive</button></div><div class="subcategory-chips">${subs.map(s=>`<span class="subcategory-chip">${escapeHtml(s.name)}</span>`).join('')||'<span class="subcategory-chip">No subcategories</span>'}</div></div>`}).join('');$('categoryManager').innerHTML=groups||'<div class="simple-empty">No categories.</div>';$$('[data-archive-category]').forEach(b=>b.onclick=()=>archiveCategory(b.dataset.archiveCategory))}
  function applyTheme(){let theme=state.settings?.theme||'system';if(theme==='system')theme=window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.body.classList.toggle('dark',theme==='dark')}

  // SELECTS & MODALS
  function populateCategorySelects(){const txType=$('txType')?.value||'expense';const cats=state.categories.filter(c=>c.category_type===txType);$('txCategory').innerHTML='<option value="">Select category</option>'+cats.map(c=>`<option value="${c.id}">${escapeHtml(c.icon||'')} ${escapeHtml(c.name)}</option>`).join('');const expenseCats=state.categories.filter(c=>c.category_type==='expense');$('budgetCategory').innerHTML=expenseCats.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');$('parentCategory').innerHTML=state.categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)} (${c.category_type})</option>`).join('');populateSubcategories()}
  function populateSubcategories(){const cid=$('txCategory').value;const subs=state.subcategories.filter(s=>s.category_id===cid);$('txSubcategory').innerHTML='<option value="">None</option>'+subs.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('')}
  $('txType').onchange=populateCategorySelects;$('txCategory').onchange=populateSubcategories;
  function openModal(id){$(id).classList.remove('hidden')}
  function closeModal(id){$(id).classList.add('hidden')}
  $$('[data-close-modal]').forEach(b=>b.onclick=()=>closeModal(b.dataset.closeModal));
  function openTransaction(type='expense'){const f=$('transactionForm');f.reset();$('transactionId').value='';$('txDate').value=today();$('txType').value=type;populateCategorySelects();$('transactionModalTitle').textContent=type==='income'?'Add Income':type==='expense'?'Add Expense':'Add Transfer';openModal('transactionModal')}
  $('addTransactionButton').onclick=()=>openTransaction('expense');$('floatingAddButton').onclick=()=>openTransaction('expense');$$('[data-add-type]').forEach(b=>b.onclick=()=>openTransaction(b.dataset.addType));
  function openEditTransaction(id){const t=state.transactions.find(x=>x.id===id);if(!t)return;$('transactionId').value=t.id;$('txType').value=t.transaction_type;populateCategorySelects();$('txAmount').value=t.amount;$('txDate').value=t.transaction_date;$('txCategory').value=t.category_id||'';populateSubcategories();$('txSubcategory').value=t.subcategory_id||'';$('txMerchant').value=t.merchant||'';$('txPayment').value=t.payment_method||'Checking Account';$('txDescription').value=t.description||'';$('txNotes').value=t.notes||'';$('txRecurring').checked=!!t.is_recurring;$('transactionModalTitle').textContent='Edit Transaction';openModal('transactionModal')}

  // CRUD - TRANSACTION
  $('transactionForm').onsubmit=async e=>{e.preventDefault();const id=$('transactionId').value,payload={user_id:state.session.user.id,transaction_type:$('txType').value,amount:Number($('txAmount').value),transaction_date:$('txDate').value,category_id:$('txCategory').value||null,subcategory_id:$('txSubcategory').value||null,merchant:$('txMerchant').value.trim()||null,payment_method:$('txPayment').value,description:$('txDescription').value.trim()||null,notes:$('txNotes').value.trim()||null,is_recurring:$('txRecurring').checked};const q=id?db.from('transactions').update(payload).eq('id',id):db.from('transactions').insert(payload);const {error}=await q;if(error)return showToast(error.message);closeModal('transactionModal');showToast(id?'Transaction updated.':'Transaction saved.');await loadTransactions();renderAll()}
  async function deleteTransaction(id){if(!confirm('Delete this transaction?'))return;const {error}=await db.from('transactions').delete().eq('id',id);if(error)return showToast(error.message);await loadTransactions();renderAll();showToast('Transaction deleted.')}

  // BUDGET CRUD
  $('openBudgetModal').onclick=()=>{$('budgetMonth').value=currentMonthISO().slice(0,7);openModal('budgetModal')};
  $('budgetForm').onsubmit=async e=>{e.preventDefault();const month=$('budgetMonth').value+'-01';const payload={user_id:state.session.user.id,category_id:$('budgetCategory').value,budget_month:month,amount:Number($('budgetAmountInput').value)};const {error}=await db.from('budgets').upsert(payload,{onConflict:'user_id,category_id,budget_month'});if(error)return showToast(error.message);closeModal('budgetModal');await loadBudgets();renderAll();showToast('Budget saved.')}
  async function deleteBudget(id){if(!confirm('Delete this budget?'))return;await db.from('budgets').delete().eq('id',id);await loadBudgets();renderAll()}

  // SAVINGS CRUD
  $('openSavingsModal').onclick=()=>openModal('savingsModal');
  $('savingsForm').onsubmit=async e=>{e.preventDefault();const payload={user_id:state.session.user.id,name:$('goalName').value.trim(),target_amount:Number($('goalTarget').value),target_date:$('goalDate').value||null,notes:$('goalNotes').value.trim()||null,status:'active'};const {error}=await db.from('savings_goals').insert(payload);if(error)return showToast(error.message);closeModal('savingsModal');e.target.reset();await loadSavings();renderAll();showToast('Savings goal created.')}
  function openContribution(id){$('contributionGoalId').value=id;$('contributionDate').value=today();$('contributionAmount').value='';$('contributionNote').value='';openModal('contributionModal')}
  $('contributionForm').onsubmit=async e=>{e.preventDefault();const payload={user_id:state.session.user.id,goal_id:$('contributionGoalId').value,amount:Number($('contributionAmount').value),contribution_date:$('contributionDate').value,note:$('contributionNote').value.trim()||null};const {error}=await db.from('savings_contributions').insert(payload);if(error)return showToast(error.message);closeModal('contributionModal');await loadSavings();renderAll();showToast('Contribution added.')}
  async function completeGoal(id){await db.from('savings_goals').update({status:'completed'}).eq('id',id);await loadSavings();renderAll();showToast('Goal completed! 🐾')}
  async function deleteGoal(id){if(!confirm('Delete this goal and its contribution history?'))return;await db.from('savings_goals').delete().eq('id',id);await loadSavings();renderAll()}

  // DEBT CRUD
  $('openDebtModal').onclick=()=>openModal('debtModal');
  $('debtForm').onsubmit=async e=>{e.preventDefault();const payload={user_id:state.session.user.id,name:$('debtName').value.trim(),debt_type:$('debtType').value,original_amount:Number($('debtOriginal').value),current_balance:Number($('debtBalance').value),monthly_payment:Number($('debtPayment').value||0),interest_rate:$('debtRate').value?Number($('debtRate').value):null,due_day:$('debtDueDay').value?Number($('debtDueDay').value):null,expected_end_date:$('debtEndDate').value||null,notes:$('debtNotes').value.trim()||null,status:'active'};const {error}=await db.from('debts').insert(payload);if(error)return showToast(error.message);closeModal('debtModal');e.target.reset();await loadDebts();renderAll();showToast('Debt / EMI added.')}
  function openDebtPayment(id){const d=state.debts.find(x=>x.id===id);$('debtPaymentId').value=id;$('debtPaymentAmount').value=d?.monthly_payment||'';$('debtPaymentDate').value=today();$('debtPaymentNote').value='';openModal('debtPaymentModal')}
  $('debtPaymentForm').onsubmit=async e=>{e.preventDefault();const id=$('debtPaymentId').value,d=state.debts.find(x=>x.id===id),amt=Number($('debtPaymentAmount').value);const {error}=await db.from('debt_payments').insert({user_id:state.session.user.id,debt_id:id,amount:amt,payment_date:$('debtPaymentDate').value,note:$('debtPaymentNote').value.trim()||null});if(error)return showToast(error.message);const newBal=Math.max(0,Number(d.current_balance)-amt);await db.from('debts').update({current_balance:newBal,status:newBal<=0?'paid':'active'}).eq('id',id);closeModal('debtPaymentModal');await loadDebts();renderAll();showToast('Payment recorded.')}
  async function markDebtPaid(id){await db.from('debts').update({current_balance:0,status:'paid'}).eq('id',id);await loadDebts();renderAll()}
  async function deleteDebt(id){if(!confirm('Delete this debt and its payment history?'))return;await db.from('debts').delete().eq('id',id);await loadDebts();renderAll()}

  // CATEGORY CRUD
  $('openCategoryModal').onclick=()=>openModal('categoryModal');
  $('categoryMode').onchange=()=>{const sub=$('categoryMode').value==='subcategory';$('categoryTypeLabel').classList.toggle('hidden',sub);$('categoryIconLabel').classList.toggle('hidden',sub);$('parentCategoryLabel').classList.toggle('hidden',!sub)};
  $('categoryForm').onsubmit=async e=>{e.preventDefault();const mode=$('categoryMode').value,name=$('newCategoryName').value.trim();let error;if(mode==='category'){({error}=await db.from('categories').insert({user_id:state.session.user.id,category_type:$('newCategoryType').value,name,icon:$('newCategoryIcon').value.trim()||null,sort_order:999}))}else{({error}=await db.from('subcategories').insert({user_id:state.session.user.id,category_id:$('parentCategory').value,name,sort_order:999}))}if(error)return showToast(error.message);closeModal('categoryModal');e.target.reset();await loadCategories();renderAll();showToast('Category saved.')}
  async function archiveCategory(id){if(!confirm('Archive this category? Existing transactions stay safe.'))return;const {error}=await db.from('categories').update({is_archived:true}).eq('id',id);if(error)return showToast(error.message);await loadCategories();renderAll()}

  // PROFILE & THEME
  $('saveProfileButton').onclick=async()=>{const name=$('settingsName').value.trim()||'Anna';const {error}=await db.from('profiles').update({display_name:name,currency:$('settingsCurrency').value,date_format:$('settingsDateFormat').value}).eq('id',state.session.user.id);if(error)return showToast(error.message);await loadProfile();renderAll();showToast('Profile saved.')}
  $('themeSelect').onchange=async()=>{const theme=$('themeSelect').value;await db.from('user_settings').upsert({user_id:state.session.user.id,theme},{onConflict:'user_id'});state.settings={...(state.settings||{}),theme};applyTheme();renderAll()}
  $('sendResetButton').onclick=async()=>{const email=state.session.user.email;const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:cfg.siteUrl});showToast(error?error.message:'Password reset email sent.')}

  // EXPORT / RESTORE
  function download(name,text,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function csvText(){const rows=[['Date','Type','Amount','Category','Subcategory','Merchant','Description','Payment Method','Recurring','Notes'],...state.transactions.map(t=>[t.transaction_date,t.transaction_type,t.amount,categoryName(t),subcategoryName(t),t.merchant||'',t.description||'',t.payment_method||'',t.is_recurring?'Yes':'No',t.notes||''])];return rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')}
  function exportCsv(){download(`PawBudget_Transactions_${today()}.csv`,csvText(),'text/csv')}
  $('exportCsvButton').onclick=exportCsv;$('settingsExportCsv').onclick=exportCsv;
  $('exportJsonButton').onclick=()=>{const data={exported_at:new Date().toISOString(),profile:state.profile,settings:state.settings,categories:state.categories,subcategories:state.subcategories,transactions:state.transactions,budgets:state.budgets,savings_goals:state.goals,savings_contributions:state.contributions,debts:state.debts,debt_payments:state.debtPayments};download(`PawBudget_Backup_${today()}.json`,JSON.stringify(data,null,2),'application/json')};
  $('restoreJsonInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!confirm('Merge this backup into PawBudget? Existing data will not intentionally be deleted.'))return;try{const data=JSON.parse(await file.text()),uid=state.session.user.id;const tx=(data.transactions||[]).map(({id,created_at,updated_at,categories,subcategories,...x})=>({...x,user_id:uid}));if(tx.length){const {error}=await db.from('transactions').insert(tx);if(error)throw error}showToast('Backup merged.');await loadAll()}catch(err){showToast(`Restore failed: ${err.message}`)}};

  // NAVIGATION & FILTERS
  function openPage(name){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$$('.page').forEach(p=>p.classList.remove('active'));$(`${name}-page`)?.classList.add('active');$('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>renderAll(),10)}
  $$('.nav-item').forEach(b=>b.onclick=()=>openPage(b.dataset.page));$$('[data-page-link]').forEach(b=>b.onclick=()=>openPage(b.dataset.pageLink));$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');
  $$('#dashboardPeriods .period').forEach(b=>b.onclick=()=>{$$('#dashboardPeriods .period').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.dashboardPeriod=b.dataset.period;renderDashboard()});
  $('prevMonth').onclick=()=>{state.dashboardMonth=new Date(state.dashboardMonth.getFullYear(),state.dashboardMonth.getMonth()-1,1);state.dashboardPeriod='month';$$('#dashboardPeriods .period').forEach(x=>x.classList.toggle('active',x.dataset.period==='month'));renderDashboard()};$('nextMonth').onclick=()=>{state.dashboardMonth=new Date(state.dashboardMonth.getFullYear(),state.dashboardMonth.getMonth()+1,1);state.dashboardPeriod='month';$$('#dashboardPeriods .period').forEach(x=>x.classList.toggle('active',x.dataset.period==='month'));renderDashboard()};
  $('reportPeriod').onchange=renderReports;['historySearch','historyType','historyCategory','historyFrom','historyTo'].forEach(id=>$(id).oninput=()=>{state.historyPage=1;renderHistory()});$('clearHistoryFilters').onclick=()=>{$('historySearch').value='';$('historyType').value='all';$('historyCategory').value='all';$('historyFrom').value='';$('historyTo').value='';state.historyPage=1;renderHistory()};$('historyPrev').onclick=()=>{state.historyPage--;renderHistory()};$('historyNext').onclick=()=>{state.historyPage++;renderHistory()};
  $('globalSearch').oninput=e=>{const q=e.target.value.trim();if(!q)return;openPage('history');$('historySearch').value=q;state.historyPage=1;renderHistory()};

  db.auth.getSession().then(({data})=>{if(data.session)enterApp(data.session)});
  db.auth.onAuthStateChange(async(event,session)=>{
    if(event==='SIGNED_OUT'){location.reload();return}
    if(session) state.session=session;
    if(event==='PASSWORD_RECOVERY' && session){
      const next=window.prompt('Enter your new PawBudget password (at least 6 characters):');
      if(next && next.length>=6){
        const {error}=await db.auth.updateUser({password:next});
        showToast(error?error.message:'Password updated successfully.');
      }
    }
  });
})();